version: '3.8'

services:
  jenkins:
    build:
      context: /tmp
      dockerfile: /tmp/Dockerfile
    container_name: jenkins
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    external: true